/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * mal.kg API
 * API для доски объявлений mal.kg
 * OpenAPI spec version: 1.0.0
 */

export type GetUsersIdFavoritesParams = {
  /**
   * Номер страницы
   */
  page?: number;
  /**
   * Количество элементов на странице
   */
  limit?: number;
};
