/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * mal.kg API
 * API для доски объявлений mal.kg
 * OpenAPI spec version: 1.0.0
 */

export * from "./getAdsParams";
export * from "./getFavoritesUserIdAdIdCheck200";
export * from "./getFavoritesUserIdCount200";
export * from "./getUsersIdFavorites200";
export * from "./getUsersIdFavoritesParams";
export * from "./postAdsBody";
export * from "./postAuthLoginBody";
export * from "./postAuthRefreshBody";
export * from "./postAuthRegisterBody";
export * from "./postAuthVerifyBody";
export * from "./putAdsIdBody";
export * from "./user";
export * from "./userRole";
export * from "./userUpdate";
