/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * mal.kg API
 * API для доски объявлений mal.kg
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from "./userRole";

export interface User {
  /** ID пользователя */
  _id?: string;
  /** Имя пользователя */
  name?: string;
  /** Номер телефона */
  phone?: string;
  /** URL аватара */
  avatar?: string;
  /** Роль пользователя */
  role?: UserRole;
  /** Заблокирован ли пользователь */
  isBlocked?: boolean;
  /** Дата создания */
  createdAt?: string;
  /** Дата обновления */
  updatedAt?: string;
}
